### ISSUE TITLE
Add support for Akka Streams

### ISSUE THREAD

**Issue by schrepfler** [erikvanoosten/metrics-scala#100]
It would be nice if there would be some support for akka streams.
https://github.com/ruippeixotog/akka-stream-mon for example allows to capture Throughput and Latency metrics.
Probably it would be nice if there's a way to capture if the stream is connected or disconnected (maybe based on on info from the stream supervisor?) or by emitting events from a RestartSource which would trigger a boolean flag on/off or keeping a counter between 0-1 not sure what's the best way to model this.

**Comment by erikvanoosten** [comment]
Hi @schrepfler , that sounds like a nice idea. It sounds easy to forward akka-stream-mon's events to dropwizard metrics. The other features you're requesting would need a PR; I do not use akka-streams myself, it would be hard for me to support that.
Are you willing to give a go?

**Comment by scullxbones** [comment]
> I do not use akka-streams myself, it would be hard for me to support that.

Hey @erikvanoosten - I use streams fairly regularly.  I'm happy to help support or with the PR review, just let me know.

**Comment by erikvanoosten** [comment]
It seems there is currently no interest to create a pull request for this feature. So I am closing this for now.
