### ISSUE TITLE
Scala 2.13.0-RC2

### ISSUE THREAD

**Issue by erikvanoosten** [erikvanoosten/metrics-scala#149]

**Comment by erikvanoosten** [comment]
No longer depends on Akka https://github.com/akka/akka/issues/26964.
Still blocked by mockito-scala.

**Comment by magnolia-k** [comment]
mockito-scala 1.4.7 for Scala 2.13.0-RC2 is released!

https://search.maven.org/artifact/org.mockito/mockito-scala_2.13.0-RC2/1.4.7/jar

**Comment by magnolia-k** [comment]
@erikvanoosten 

mockito-scala 1.5.2 for Scala 2.13.0-RC3 is released!

https://search.maven.org/artifact/org.mockito/mockito-scala_2.13.0-RC3/1.5.2/jar

akka-actor 2.5.23 for Scala 2.13.0-RC3 is released!

https://search.maven.org/artifact/com.typesafe.akka/akka-actor_2.13.0-RC3/2.5.23/jar

**Comment by erikvanoosten** [comment]
Super seeded by a 2.13.0-RC3 release: 4.0.6.
