### ISSUE TITLE
MetricName.append breaks in v4

### ISSUE THREAD

**Issue by franzneubert0815** [erikvanoosten/metrics-scala#162]
Hey,

we noticed that `MetricName.append` behaves differently in v4.x.x than before, when `append` is called on an empty `MetricName`:

```scala
// v3
MetricName("").append("foo", "bar") // results in "foo.bar"

// v4
MetricName("").append("foo", "bar") // results in ".foo.bar"
```

I suspect this was introduced with #117

**Comment by erikvanoosten** [comment]
Hi Franz,
Interesting! This behavior is according to specification still :slightly_smiling_face: .

Do you depend on this behavior or can we just add a few `require(name.nonEmpty)` here and there?

**Comment by erikvanoosten** [comment]
Hi Franz,
Interesting! This behavior is according to specification still slightly_smiling_face . (It only says something about nulls.)

Do you depend on this behavior or can we just add a few require(name.nonEmpty) here and there? What do you expect when you call .append("")? (Never mind. I see that .append("") will skip the addition.)

We can't have the case that the final name is empty. So I propose we don't allow an empty string as parameter to MetricName.

**Comment by michaelarndt0423** [comment]
Hi Eric,
a general `require(name.nonEmpty)` is a quite hard change and would lead to even more workarounds at least on our side. But in conjunction with a `MetricName.empty()` this could work, and the MetricName instance could carry the optional separator char itself which for `MetricName.empty` would be empty and for every other it would be `Some('.')`. 
Cheers,
Michael
(working alongside Franz)

**Comment by erikvanoosten** [comment]
`MetricName.empty` has the same problem as allowing an empty string in `MetricName(String)`: it allows you to construct empty metric names. It is a nicer API though. I have to think about this a bit.

**Comment by michaelarndt0423** [comment]
Hi Erik. It all arises from the `MetricBuilder` that has a `baseName` that needs to be (at least in our case) something artificial or empty. If the baseName could be optional I would be fine with the `require()`. But putting baseName to be optional would be a quite hard change (`InstrumentedBuilder`, ...)

**Comment by erikvanoosten** [comment]
I understand. Don't worry, I don't want to cut off your use case.

**Comment by erikvanoosten** [comment]
@franzneubert0815 v4.0.8 will have a very simple fix which will allow the old behavior again. Thanks for reporting the issue!
