### ISSUE TITLE
Spark: Exception in thread "main" java.lang.NoSuchMethodError: com.codahale.metrics.MetricRegistry.timer(Ljava/lang/String;Lcom/codahale/metrics/MetricRegistry$MetricSupplier;)Lcom/codahale/metrics/Timer;

### ISSUE THREAD

**Issue by pederpansen** [erikvanoosten/metrics-scala#190]
Hi.

When running a "fat JAR" build by `sbt assembly` for a Spark job against your library, I'm seeing the following runtime exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.codahale.metrics.MetricRegistry.timer(Ljava/lang/String;Lcom/codahale/metrics/MetricRegistry$MetricSupplier;)Lcom/codahale/metrics/Timer;
	at nl.grons.metrics4.scala.HdrMetricBuilder.timer(HdrMetricBuilder.scala:59)
```

I'm not quite sure what to make of it, as everything seems to be in order. I'm using the following library versions:
- `io.dropwizard.metrics:metrics-core:4.1.0`
- `nl.grons:metrics4-scala-hdr_2.11:4.0.8`
- `org.mpierce.metrics.reservoir:hdrhistogram-metrics-reservoir:1.1.0`

Any ideas?

**Comment by pederpansen** [comment]
I just realized that Spark 2.4 ships with `io.dropwizard.metrics:metrics-core:3.1.5` included. Oh my.

**Comment by erikvanoosten** [comment]
That should actually be fine. Metrics-core 4.0.1 should be binary compatible with 3.1.5.

**Comment by pederpansen** [comment]
Hi @erikvanoosten,  unfortunately it is not completely compatible. The method `com.codahale.metrics.MetricRegistry.timer(String, MetricSupplier)`, which is used [here](https://github.com/erikvanoosten/metrics-scala/blob/2a994ad2bffe4e70408d725e31db5750ece7c760/metrics-scala-hdr/src/main/scala/nl/grons/metrics4/scala/HdrMetricBuilder.scala#L61), does not exist in 3.x versions of dropwizard's `metrics-core`.

For anyone stumbling over this, I fixed it by shading the dependency via the `sbt-assemly` plugin. Relevant snippet from `build.sbt`:

```
assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("com.codahale.metrics.**" -> "shaded.com.codahale.metrics.@1").inAll
)
```
Make sure to use a recent version of `sbt-assembly` like `0.14.10`, otherwise you might see ugly stacktraces: https://github.com/sbt/sbt-assembly/issues/347

I am aware this is a dirty hack, you should probably integrate with Spark's own monitoring facilities instead, see https://spark.apache.org/docs/latest/monitoring.html#metrics

**Comment by erikvanoosten** [comment]
You can also consider using an older compatible metrics-scala.

**Comment by pederpansen** [comment]
Yes, it would probably the best to just use a Spark-compatible version. However, in my company there was already some tooling built around another version and it was easier to just shade the lib.
