### ISSUE TITLE
Memory leak on re-registering gauges

### ISSUE THREAD

**Issue by choojoyq** [erikvanoosten/metrics-scala#200]
In my long running application i use a background thread to run some process that could be restarted. I use a gauge to monitor a state of this process. When restart occurs i unregister current gauge and register a new one with the same name. However this gauge isn't fully unregistered because ``MetricBuilder`` stores all the registered gauges internally. These unregistered gauges are accumulated and OOM occurs after several restarts. 
I could submit a PR for this issue but i'm not sure what is the proper fix so some should help me with this.

**Comment by erikvanoosten** [comment]
Hi @choojoyq , did you already try calling `MetricBuilder.unregisterGauges()`?

**Comment by choojoyq** [comment]
Hi @erikvanoosten, seems that this method unregisters all the gauges, is it acceptable to invoke it for a single one?

**Comment by erikvanoosten** [comment]
It only unregisters the gauges that were registered via that particular MetricBuilder.

**Comment by erikvanoosten** [comment]
In `ActorInstrumentedLifeCycle` you can find an example where we use it to unregister gauges created from an Actor right before it restarts.

**Comment by choojoyq** [comment]
I see, so seems that i should use a distinct ``MetricBuilder`` for my background service and unregister all the gauges on restart?

**Comment by erikvanoosten** [comment]
Yes, that is correct. Mind you, you get a distinct `MetricBuilder` in each instance of classes that extends `DefaultInstrumented` (or `InstrumentedBuilder`). So you might already have a distinct instance!

**Comment by erikvanoosten** [comment]
To add to the previous comment: assuming your background service extends `DefaultInstrumented`, you can just invoke `metrics.unregisterGauges()` during the restart.

**Comment by choojoyq** [comment]
Got it, thanks for quick response!

**Comment by erikvanoosten** [comment]
I added a note in the manul: https://github.com/erikvanoosten/metrics-scala/blob/master/docs/Manual.md#gauges

**Comment by choojoyq** [comment]
Just a question, should it be probably possible to unregister a single ``gauge`` in case of an absence of a distinct ``MetricsRegistry``? Seems that distinct ``MetricRegistry`` requires a distinct reporter

**Comment by erikvanoosten** [comment]
Please don't confuse `MetricBuilder` (from metrics-scala) with `MetricRegistry` (from metrics-core)! You will typically use many many `MetricBuilder`s on top of a single `MetricRegistry`.

So far I have not seen use cases for individual un-registration of gauges in `MetricBuilder`. Usually you can write your gauge such that there is no need to re-register it.

BTW, `MetricRegistry` does have an unregister method (its called `remove`). However, you should not use it directly because `MetricBuilder` also keeps a reference to each gauge.
