### ISSUE TITLE
Make constructors of PushGauge and PushGaugeWithTimeout not private

### ISSUE THREAD

**Issue by nykh** [erikvanoosten/metrics-scala#397]
These two classes are very useful addition for monitoring. Unfortunately, their constructors are defined as `private[scala]`, making it impossible for lib user to extend it. Would it be possible to consider making their constructor not private?

**Comment by erikvanoosten** [comment]
@nykh Could you tell a bit more about your use case? What are you trying to achieve?

**Comment by erikvanoosten** [comment]
Closing due to lack of input. Feel free to re-open this issue when there is more input.
