### ISSUE TITLE
support for the new pekko open source akka

### ISSUE THREAD

**Issue by normana400** [erikvanoosten/metrics-scala#482]
offer a library that offers drop wizard support for the new pekko library (open source akka fork).
pekko version 1.0.1 is essentially akka 2.6.x but with package name (and config name changes) in its implementation

 https://pekko.apache.org/docs/pekko/current/project/migration-guides.html

**Comment by erikvanoosten** [comment]
This is included in version 4.3.0 that was just released. 🥳
