### ISSUE TITLE
No mention of 3.2.0 in GitHub releases page

### ISSUE THREAD

**Issue by maciej** [erikvanoosten/metrics-scala#49]
Hey!

There is no mention of the most recent version (3.2.0) of the library in the GitHub releases page: https://github.com/erikvanoosten/metrics-scala/releases. That's for me, and I suppose not only me, the first place to look for the current version of any software component I'm using.
The latest version I see there is 3.0.3, which is confusing.

**Comment by erikvanoosten** [comment]
I changed the release process so that I won't forget to set git tags any more :)  Since the tags show up on the release page I am considering this issue solved.

**Comment by maciej** [comment]
:+1:
