### ISSUE TITLE
Weird version number for 4.3.3

### ISSUE THREAD

**Issue by mccartney** [erikvanoosten/metrics-scala#556]
After `4.3.2` the next version which got released is:
```
4.3.3+0-68d2004e+20241007-1150/
```

Not fully sure if this is intended. Is it some new versioning schema applied or some mistake creeping in?

See e.g.
https://repo1.maven.org/maven2/nl/grons/metrics4-scala_2.12/
<img width="690" alt="image" src="https://github.com/user-attachments/assets/a1bd2390-2e27-4e59-8ad4-7049f154ae4c">

**Comment by mccartney** [comment]
I fail to see any commit in the recent ones (since 4.3.2) which would directly call for this.
So I guess this is an effect of some upstream dependency upgrade. `sbt-sonatype`?

**Comment by erikvanoosten** [comment]
It must have been my error while doing the release. I should really automate it...

**Comment by erikvanoosten** [comment]
Yes, I see now. I tagged 1 commit to early 😞

**Comment by erikvanoosten** [comment]
I have now released from the commit tagged 4.3.3, meaning that 4.3.3 is now properly on maven central.

Thanks for the report @mccartney !
