### ISSUE TITLE
Request for build against metrics-core 3.0.1

### ISSUE THREAD

**Issue by rsandberg-xad** [erikvanoosten/metrics-scala#57]
Looking for a build against metrics-core 3.0.1 (scala 2.11) - the most recent stable release. 3.1.0 has some issues with graphite:
https://github.com/dropwizard/metrics/issues/694

**Comment by rsandberg-xad** [comment]
Correction, 3.1.0 is the current stable release, so perhaps a build with 3.0.2 re-release:
https://github.com/dropwizard/metrics/releases/tag/v3.0.2-dropwizard

Or include the patch with 3.1.0:
https://github.com/dropwizard/metrics/issues/694

**Comment by rsandberg-xad** [comment]
Disregard this request, I just saw a more comprehensive version/build matrix:
https://github.com/erikvanoosten/metrics-scala/blob/master/docs/AvailableVersions.md

**Comment by erikvanoosten** [comment]
Glad it resolved itself :)
