### ISSUE TITLE
not found: value metrics

### ISSUE THREAD

**Issue by dzlab** [erikvanoosten/metrics-scala#64]
I'm having a not found: value metrics for the `metrics` builder object. I cannot find it in the source code, how I can import this one?

**Comment by erikvanoosten** [comment]
Hi @diab, did you follow the readme on github?

**Comment by erikvanoosten** [comment]
If you are only interested in the code, its [here](https://github.com/erikvanoosten/metrics-scala/blob/master/src/main/scala/nl/grons/metrics/scala/InstrumentedBuilder.scala).

**Comment by dzlab** [comment]
ah I have to extend the `Instrumented` trait as in https://github.com/erikvanoosten/metrics-scala/blob/master/docs/Manual.md

**Comment by erikvanoosten** [comment]
Indeed. Good luck! :)
