### ISSUE TITLE
Build against 2.4.0-RC2

### ISSUE THREAD

**Issue by ddispaltro** [erikvanoosten/metrics-scala#65]
Since akka 2.4 is now in RC2 would you mind doing a build against that?

**Comment by scullxbones** [comment]
I will definitely need to in order to implement Tagging for the ReadJournal.

Is there something that is backward incompatible between RC1 and RC2?  If not, the akka dependencies can be overridden in the application's build tooling (sbt,maven,etc).

**Comment by scullxbones** [comment]
It's probably a good time to think about consolidating versions - quite a matrix is maintained currently between akka versions as well as scala, especially with scala 2.12 on the horizon, which drops java 7 support.

That said, the akka team has worked to make akka 2.4 binary backward compatible with 2.3 - is there an issue you're seeing with akka 2.4 and `metrics-scala`?

**Comment by ddispaltro** [comment]
Your right, I've had no problems.
