### ISSUE TITLE
Hdrhistogram manual page little bit vague

### ISSUE THREAD

**Issue by note** [erikvanoosten/metrics-scala#66]
`Hdrhistogram.md` states:

```
in addition, you should probably override the dependency to HdrHistogram. E.g.:

libraryDependencies += "org.hdrhistogram" % "HdrHistogram" % "2.1.6"

See the README to see which version(s) you can use.
```

In both `README` and `AvailableVersions.md` there is a table with column `Hdr version` but numbers put in this column seems to be versions of `hdrhistogram-metrics-reservoir` not HdrHistogram itself.

It may be confusing and actually it is for me :) I've overriden HdrHistogram to 2.1.7 (which is the most recent version) but not completely sure if it's non-breaking and the sentence `See the README to see which version(s) you can use` suggest that README can help me in being sure about it but it's not. I suggest either changing this sentence or extending README to contain information about "suggested" HdrHistogram version.

Also, how can I find out that `HdrHistogram` 2.1.7 will work with `hdrhistogram-metrics-reservoir` 1.1.0 - HdrHistogram does not seem to have changelog.

Actually I am not sure if this can be considered an "issue". I would rather ask first on user group forum, but AFAIK there's no user group for metrics-scala so I am asking here :)

**Comment by erikvanoosten** [comment]
Hi @note , please let me know when you see more improvements for the documentation.

> Also, how can I find out that HdrHistogram 2.1.7 will work with hdrhistogram-metrics-reservoir 1.1.0 - HdrHistogram does not seem to have changelog.

Well, you can't :(   You will have to ask the author, read the source, or just try it out.

> Actually I am not sure if this can be considered an "issue".

An issue is fine. You did find a bug in the documentation :)

> I would rather ask first on user group forum, but AFAIK there's no user group for metrics-scala so I am asking here :)

Metrics-scala support can also be obtained via the metrics user list (http://groups.google.com/group/metrics-user).

**Comment by note** [comment]
@erikvanoosten thank you for reply :)

I noticed one thing in your change - in all places you used `2.1.6` except of one place in which you used `2.1.7` - is it deliberate?

**Comment by erikvanoosten** [comment]
Yes, that is on purpose. Metrics 3.5.2 pulls in `hdrhistogram-metrics-reservoir` `1.1.0`, which transitively pulls in `HdrHistogram` `2.1.6`. This is reflected in the versions overview.

The documentation tells that we can (probably) upgrade `HdrHistogram` to `2.1.7` because that has since become available.

**Comment by note** [comment]
Now I see your point.

Just wondering if it's a good approach to encourage people to upgrade version even though it's not completely clear it will work. Is it a convention that minor versions of `HdrHistogram` are compatible? I have no clue about this and suspect you have a better grasp in that subject :)

**Comment by erikvanoosten** [comment]
Yeah, good point. In general minor releases are compatible. But indeed, you can't be sure. Also given that these libs have no release notes, maybe it's better to remove this advise.

**Comment by erikvanoosten** [comment]
Okay, I'll remove it this evening. Thanks for your thoughts @note.
