### ISSUE TITLE
Artifact missing for metrics-scala_2.11-3.5.2_a2.3 in JCenter

### ISSUE THREAD

**Issue by maciej** [erikvanoosten/metrics-scala#67]
Hi,

The jar for metrics-scala_2.11-3.5.2_a2.3 is missing from JCenter repository. I'm not sure if JCenter mirrors Maven Central or do you push `metrics-scala` manually there.
The pom file for the same artifact version is present, though. Previous version is unaffected.

See https://jcenter.bintray.com/nl/grons/metrics-scala_2.11/3.5.2_a2.3/

**Comment by erikvanoosten** [comment]
I push the artifacts to maven central. The jar is present there (http://central.maven.org/maven2/nl/grons/metrics-scala_2.11/3.5.2_a2.3/metrics-scala_2.11-3.5.2_a2.3.jar). I am afraid you will have to contact JCenter.

**Comment by maciej** [comment]
@erikvanoosten OK, let's see what happens: https://twitter.com/maciejb/status/646327124685639680

**Comment by maciej** [comment]
OK, Bintray fixed the issue: https://jcenter.bintray.com/nl/grons/metrics-scala_2.11/3.5.2_a2.3/
