### ISSUE TITLE
Update Akka to 2.4.1

### ISSUE THREAD

**Issue by ngocdaothanh** [erikvanoosten/metrics-scala#71]
Akka 2.4.x has been released:
http://akka.io/news/2015/09/30/akka-2.4.0-released.html

BIG changes:
* Java 8 is required.
* Dropped support for Scala 2.10.

Migration Guide 2.3.x to 2.4.x:
http://doc.akka.io/docs/akka/2.4.1/project/migration-guide-2.3.x-2.4.x.html

2.4.x is basically binary compatible with 2.3.x, but because it's a major version, may be you should release an new version of metrics-scala for it?

**Comment by erikvanoosten** [comment]
Hi @ngocdaothanh thanks for thinking along. Please know that creating a release is not peanuts. I need to take a lot of manual steps and it easily takes 3 hours. I don't want to spend my time (I am a father too) unless there is a real benefit.
