### ISSUE TITLE
Make it easy to change the reservoir of histograms and timers

### ISSUE THREAD

**Issue by LannyRipple** [erikvanoosten/metrics-scala#72]
I have a long running job that I want to know the lifetime distribution on processing work rather than the last 5 minutes or so.  Changing the reservoir on my timer was painful.  Please expose modifying the reservoir.

Best I got was

```scala
private[this] val splitTimer = {
    // metricNameFor() is protected
    val name = metrics.baseName.append("split.times").name
    new scala.Timer(metrics.registry.register( name, new Timer(new UniformReservoir())) )
}
```

**Comment by erikvanoosten** [comment]
Hello @LannyRipple, how would a more convenient method look like for you?

**Comment by erikvanoosten** [comment]
Hello @LannyRipple, are you still interested in this issue?

**Comment by erikvanoosten** [comment]
Without more information on how this is used (just once, for all timer, etc.) there is nothing I can do. Closing this issue.
