### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by notxcain** [erikvanoosten/metrics-scala#73]
Latest changes were made 6 month ago. 
We depend on this library in production.
@erikvanoosten if you don't have time for this library please assign collaborators to maintain this project.

Thanks!

**Comment by erikvanoosten** [comment]
Hi @notxcain . Yes it is maintained. I have not yet found a good way to solve #69 but for the rest, what kind of maintenance is necessary at the moment?

**Comment by notxcain** [comment]
@erikvanoosten great to hear that :) I wonder whether we should crossbuild it against latest Akka 2.4.2

**Comment by erikvanoosten** [comment]
There is no need for that. Akka 2.4 is binary compatible with Akka 2.3.

**Comment by scullxbones** [comment]
I use with akka 2.4 today in production (soon 2.4.2), with no compatibility issues.

**Comment by erikvanoosten** [comment]
I just realized I never made @scullxbones a collaborator. Just fixed that ;)

**Comment by erikvanoosten** [comment]
@notxcain please create issues in case you have ideas, bugs etc. For now I am going to close this.
