### ISSUE TITLE
Gauge calling method that returns a future

### ISSUE THREAD

**Issue by francisdb** [erikvanoosten/metrics-scala#76]
```
Gauge[Integer]{
  taskManager.countTasks()
}
```

countTasks returns a `Future[Int]`

Would be nice to have a Gauge that accepts futures or is this a bad idea?

**Comment by erikvanoosten** [comment]
Hi @francisdb, thanks for your suggestion!

The metrics-scala library wraps dropwizard metrics. The Gauge interface there does not allow a future, all reporters want the value synchronously. Of course we could wrap that in the metrics-scala library which raises the question on how to await for the future: what would be the timeout, what executor context do you want to run it on? I can't answer these questions for you so you'd have to pass them along. What's left then is that metrics-scala will simply invoke what you provide. So in the end the functionality is so thin that having it in your own code adds almost no overhead.

Did I miss something?

**Comment by francisdb** [comment]
Ok, just wanted you opinion on this, currently I'm just calling Await.result which works but is suboptimal.

**Comment by scullxbones** [comment]
@francisdb one option would be to:

- create a dropwizard `Gauge` that wraps an `AtomicInt`
- add an `onSuccess` callback to your future that does an atomic update on the `AtomicInt`

This at least gets you out of the await, for a little more complexity.
