### ISSUE TITLE
Calling timeFuture inside a Spray Web Service

### ISSUE THREAD

**Issue by abhsrivastava** [erikvanoosten/metrics-scala#77]
This is more of a question than an issue. If we call the instrumentation API inside of a web service (written in spray). 

The timeFuture is written as 

`  def timeFuture[A](future: => Future[A])(implicit context: ExecutionContext): Future[A] = {
    val ctx = metric.time()
    val f = future
    f.onComplete(_ => ctx.stop())
    f
  }`

I wonder what is the impact of calling "onComplete" on the threadpool utilization of Spray.

**Comment by erikvanoosten** [comment]
There is no simple answer to your question. It depends a lot on what execution context (thread pool) is configured whether the passed in future is already complete or not. And what kind of throughput requirements you have. Note however that `ctx.stop()` has no contention (amortized) so its overhead is not large.
If we start to micro optimize, I am more worried about your use of `timeFuture` here. If you are using Spray you are already constructing a Future, and then another one to pass to `timeFuture`.

I would advise you to look into the Spray build-in options to do measurement.
