### ISSUE TITLE
Could we provide a DefaultInstrumented trait?

### ISSUE THREAD

**Issue by jklukas** [erikvanoosten/metrics-scala#79]
As of Dropwizard 1.0.0, [Dropwizard apps register their metric registry as "default" in SharedMetricRegistries](https://github.com/dropwizard/dropwizard/pull/1513). Since there's now a mechanism to discover the app's registry via `SharedMetricRegistries`, this project could define a `DefaultInstrumented` trait that points at the registry marked as "default", avoiding the need for users to define their own `Instrumented` trait unless they want to point at a non-default registry.

Would you be open to such an enhancement?

**Comment by erikvanoosten** [comment]
That sounds awesome!

**Comment by erikvanoosten** [comment]
Soon fixed by #80.
