### ISSUE TITLE
No Type Information

### ISSUE THREAD

**Issue by inrix-adasgupta** [erikvanoosten/metrics-scala#94]
Timers, Gauges, Historgrams, etc. dont have type info when exposed through JMX.

JMX object name convention (http://www.oracle.com/technetwork/java/javase/tech/best-practices-jsp-136021.html#mozTocId654884) specifies all objects should have type information.

**Comment by erikvanoosten** [comment]
Hi @inrix-adasgupta,

Thanks for your report. Unfortunately, this is the wrong project. Metrics-scala delegates all the hard work -including JMX- to dropwizard metrics. You will need to raise this issue there: https://github.com/dropwizard/metrics
