### ISSUE TITLE
Scala/Akka/Dropwizard Metrics app hanging for 10s before shutting down

### ISSUE THREAD

**Issue by zharvey-welltok** [erikvanoosten/metrics-scala#95]
I have a Scala 2.11 app that uses Akka. The [GitHub repo for it is here](https://github.com/hotmeatballsoup/akka-scala-troubleshooting). To reproduce what I'm seeing, just clone it, build it via `./gradlew fullBuild` and then run it via `java -jar build/libs/akka-scala-troubleshooting.jar` (its a self-contained executable JAR). But essentially, I'm noticing that when I kill the running JVM process via `Ctrl+C` that it takes *exactly* 10 seconds for the JAR to shut down!

IIRC, `Ctrl+C` should issue a SIGKILL to the JVM process, so how it lives for another 10 seconds thereafter is blowing my mind! Even if I'm recalling that incorrectly, I'd still like to know why my app isn't shutting down immediately (it's causing problems by not doing so).

I'm using [Dropwizard (formerly Coda Hale) Metrics](https://github.com/dropwizard/metrics) via this library. From what I can tell there might be a scheduled reporter daemon still alive that isn't shutting down right away, even when the JVM receives the SIGKILL (or whatever `Ctrl+C` is sending). Here's the main Driver (app entry point):

    object Driver extends App {
      println("Starting upp the app...")
      //SLF4JBridgeHandler.install()
      lazy val metricRegistry = new MetricRegistry()
      ConsoleReporter
        .forRegistry(metricRegistry)
        .convertRatesTo(TimeUnit.SECONDS)
        .convertDurationsTo(TimeUnit.MILLISECONDS)
        .build()
        .start(15, TimeUnit.SECONDS)

      lazy val cortex = ActorSystem("cortex")
      cortex.registerOnTermination {
        System.exit(0)
      }

      val master = cortex.actorOf(Props[Master], name = "Master")

      println("About to fire a StartUp message at Master...")
      master ! StartUp
      println("Fired! Actor system is spinning up...")
    }

When you run the JAR, you'll see this output to the logs:

    java -jar build/libs/akka-scala-troubleshooting.jar 
    Starting upp the app...
    About to fire a StartUp message at Master...
    Fired! Actor system is spinning up...
    Master has received a command to start up the actor system!
    Child will make it happen!

At this point it will just idle and do nothing -- that's fine and intended! But when I hit `Ctrl+C` on the terminal, I immediately get this log INFO:

    ^C[INFO] [08/03/2017 06:15:57.236] [Thread-0] [CoordinatedShutdown(akka://cortex)] Starting coordinated shutdown from JVM shutdown hook

Then 10 seconds goes by (exactly 10s every time), then finally a log WARNing:

    [WARN] [08/03/2017 06:16:07.248] [Thread-0] [CoordinatedShutdown(akka://cortex)] CoordinatedShutdown from JVM shutdown failed: Futures timed out after [10000 milliseconds]

**Any idea what could be going on here?**

**Comment by scullxbones** [comment]
Hi @zharvey-welltok -

While this issue isn't at all related to `metrics-scala` or even `metrics`, I thought I could provide some help:

Running `System.exit` inside a shutdown hook (`registerOnTermination`) is the problem here.  That function requires entry into a synchronized section of `java.lang.Shutdown` that a different thread is already in, thus the timeout (thankfully someone thought to put in a timeout).  You can see the behavior via use of `jstack` while in the waiting period after `Ctrl-C` but before shutdown.  E.G:

```
"cortex-akka.actor.default-dispatcher-3" #12 prio=5 os_prio=31 tid=0x00007fcd311ea000 nid=0x5303 waiting for monitor entry [0x0000700006b5d000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- waiting to lock <0x0000000795ad9978> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Runtime.exit(Runtime.java:109)
	at java.lang.System.exit(System.java:971)
	at hotmeatballsoup.Driver$$anonfun$1.apply$mcV$sp(Driver.scala:24)
        ...
```

I replaced the `System.exit` in the shutdown hook with a simple println statement and the process ended immediately on `Ctrl-C`.

Also - `Ctrl-C` translates into a SIGTERM, not a SIGKILL.  SIGKILL would immediately hard stop the java process, as you'd expect.

HTH
