### ISSUE TITLE
Wrong artifact name in Wiki

### ISSUE THREAD

**Issue by razem-io** [erikvanoosten/metrics-scala#98]
Hello,

thank you for that awesome library. I stumbled up on some artifact names which seem to be wrong.

metrics4-akka_24 should be metrics4-akka_a24
metrics4-akka_25 should be metrics4-akka_a25

Corresponding wiki entry: https://github.com/erikvanoosten/metrics-scala/blob/master/docs/AvailableVersions.md

Have a nice day!
Julian

**Comment by erikvanoosten** [comment]
Thanks @razem-io !
